services:
  deutsch-lernen:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount local data directory for database persistence
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DOCKER_ENV=true
    restart: unless-stopped