services:
  deutsch-lernen:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount your local SQLite database file
      # Replace /path/to/your/local/database with the actual path to your words.db file
      - /path/to/your/local/database:/app/data
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DOCKER_ENV=true
    restart: unless-stopped

# Alternative configuration using bind mount for a specific database file
# services:
#   deutsch-lernen:
#     build: .
#     ports:
#       - "8000:8000"
#     volumes:
#       # Direct file mount (ensure the directory exists on host)
#       - /path/to/your/words.db:/app/data/words.db
#       # Still need to mount the data directory for other potential files
#       - /path/to/your/data:/app/data
#     environment:
#       - PYTHONPATH=/app
#       - OPENAI_API_KEY=${OPENAI_API_KEY}
#       - DOCKER_ENV=true
#     restart: unless-stopped